apiVersion: v1
kind: Service
metadata:
  name: my-react-app-service
spec:
  selector:
    app: my-react-app
  ports:
  - port: 80        #The port this Service exposes internally in the cluster
    targetPort: 8080 #port we defined in dockerfile 
  type: ClusterIP # Exposes the Service on a cluster-internal IP